# Generated by Django 5.2.9 on 2025-12-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='total_time_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
